### ISSUE TITLE
Processes start simultaneously and logs are skipped

### ISSUE THREAD

**Issue by DigitalArtis4n** [mintware-de/workspace_scripts#1]
Hey 👋

I've noticed two issues with the package:

High Memory Usage from Parallel Processes
Currently, the package starts all processes at the same time. This can quickly lead to high memory usage, especially when dealing with many tasks.
Suggestion: Consider adding a queue or limiting concurrency — e.g., wait for one or a few processes to finish before starting new ones.

Missing or Skipped Logs
The success and error messages don't always appear in the console. It seems like some logs are being skipped or overwritten, which makes it hard to debug or monitor the progress.

Let me know if you need any additional info or if I can help with a PR.

Thanks for your work on this!

**Comment by devtronic** [comment]
Hi 🙂

Thanks for your input. 

**High Memory Usage from Parallel Processes**
We need to approach this problem from different angles:

_One-Shot Commands_:
For commands that run only once (e.g., `flutter build`), adding a concurrency feature should be straightforward:
```yaml
workspace_scripts:
  build:
    command: flutter
    arguments: [ 'build' ]
    concurrency: 2
```

_Background Task Commands_:
For persistent commands like `build_runner watch`, concurrency control isn't as simple since these commands run continuously until terminated.

A possible solution could involve using a delay (multiplied by the package index) or implementing a ready check pattern based on stdout:
```yaml

workspace_scripts:
  build_watch:
    command: dart
    arguments: [ 'run', 'build_runner', 'watch' ]
    delay: 3000
    concurrency: 2
    checks:
        ready: "\d+ actions completed" # 
        failed: "Failed after \d+ms" # Maybe restart the process or start the next package?
```

It might also be beneficial to add `exclude`/`include` options (paths of the packages) in these commands.

_Missing or Skipped Logs_:
Yes, I encountered the same issue but haven't yet identified the root cause.

Feel free to start working on this. I'm busy this week but can join in starting next weekend.



Edit: I cleaned up the existing code in order to make changes to the config easier: https://github.com/mintware-de/workspace_scripts/commit/93bbcd1e8900adff48d287844ea3a04d0a4f16ae

For local testing you can checkout the repo and run 
`dart pub global activate --source path /path/to/the/repo` to enable the package from sources. After that you can use `workspace_scripts run script-name` to run the script in your project
