### ISSUE TITLE
Improve concurrency

### ISSUE THREAD

**Issue by devtronic** [mintware-de/workspace_scripts#2]
**High Memory Usage from Parallel Processes**
We need to approach this problem from different angles:

_One-Shot Commands_:
For commands that run only once (e.g., `flutter build`), adding a concurrency feature should be straightforward:
```yaml
workspace_scripts:
  build:
    command: flutter
    arguments: [ 'build' ]
    concurrency: 2
```

_Background Task Commands_:
For persistent commands like `build_runner watch`, concurrency control isn't as simple since these commands run continuously until terminated.

A possible solution could involve using a delay (multiplied by the package index) or implementing a ready check pattern based on stdout:
```yaml

workspace_scripts:
  build_watch:
    command: dart
    arguments: [ 'run', 'build_runner', 'watch' ]
    delay: 3000
    concurrency: 2
    checks:
        ready: "\d+ actions completed" # 
        failed: "Failed after \d+ms" # Maybe restart the process or start the next package?
```

It might also be beneficial to add `exclude`/`include` options (paths of the packages) in these commands.
